In [1]:
import pandas as pd
import numpy as np  

print("\n------ Fetching/Reading The Data From The Data Set")
mentor = pd.read_excel('ConnectMentor.xlsx')
mentee = pd.read_excel('ConnectMentee.xlsx')
print(mentor.head()) 
print(mentee.head()) 




------ Fetching/Reading The Data From The Data Set
   Unnamed: 0               name                           email pronouns  AD  \
0           0    Veronika Durgin               durginv@gmail.com      she   0   
1           1       Spriha Ghosh  maskedaurevoirspriha@gmail.com      she   0   
2           2     Akshit Agarwal             akshit312@gmail.com      she   0   
3           3      Brown ofonime           ilinusbrown@gmail.com      she   0   
4           4  Isabel Abonitalla      isabelabonitalla@gmail.com      She   0   

  AI coding  CS  CyS  DS IT IOS robotics  SE UI  WD dropdownMenuButton  \
0  0      0   0    0  DS  0   0        0   0  0   0                EST   
1  0      0  CS    0   0  0   0        0   0  0   0                IST   
2  0      0   0    0   0  0   0        0  SE  0   0                IST   
3  0      0   0    0   0  0   0        0  SE  0   0                EET   
4  0      0   0    0   0  0   0        0   0  0  WD                PRT   

                

In [2]:
mentorFields=[]

mentorFields.append(mentor["AD"])
mentorFields.append(mentor["AI"])
mentorFields.append(mentor["coding"])
mentorFields.append(mentor["CS"])
mentorFields.append(mentor["CyS"])
mentorFields.append(mentor["DS"])
mentorFields.append(mentor["IT"])
mentorFields.append(mentor["IOS"])
mentorFields.append(mentor["robotics"])
mentorFields.append(mentor["SE"])
mentorFields.append(mentor["UI"])
mentorFields.append(mentor["WD"])

mentorFields

[0     0
 1     0
 2     0
 3     0
 4     0
 5     0
 6     0
 7     0
 8     0
 9     0
 10    0
 Name: AD, dtype: int64,
 0      0
 1      0
 2      0
 3      0
 4      0
 5     AI
 6      0
 7      0
 8      0
 9      0
 10    AI
 Name: AI, dtype: object,
 0          0
 1          0
 2          0
 3          0
 4          0
 5          0
 6          0
 7          0
 8          0
 9     coding
 10    coding
 Name: coding, dtype: object,
 0      0
 1     CS
 2      0
 3      0
 4      0
 5      0
 6      0
 7      0
 8     CS
 9     CS
 10    CS
 Name: CS, dtype: object,
 0     0
 1     0
 2     0
 3     0
 4     0
 5     0
 6     0
 7     0
 8     0
 9     0
 10    0
 Name: CyS, dtype: int64,
 0     DS
 1      0
 2      0
 3      0
 4      0
 5      0
 6      0
 7      0
 8      0
 9      0
 10    DS
 Name: DS, dtype: object,
 0      0
 1      0
 2      0
 3      0
 4      0
 5      0
 6      0
 7      0
 8      0
 9     IT
 10    IT
 Name: IT, dtype: object,
 0       0
 1       0
 

In [3]:

menteeFields=[]

menteeFields.append(mentee["AD2"])
menteeFields.append(mentee["AI2"])
menteeFields.append(mentee["coding2"])
menteeFields.append(mentee["CS2"])
menteeFields.append(mentee["CyS2"])
menteeFields.append(mentee["DS2"])
menteeFields.append(mentee["IT2"])
menteeFields.append(mentee["IOS2"])
menteeFields.append(mentee["robotics2"])
menteeFields.append(mentee["SE2"])
menteeFields.append(mentee["UI2"])
menteeFields.append(mentee["WD2"])
#menteeFields[7]

In [4]:
MatchFields=[]
for m in range (len(menteeFields)):
    Menteerows, Mentorcols = (len(menteeFields[m]),len(mentorFields[m]))
    arr=[]
    for i in range(Menteerows):
        col = []
        for j in range(Mentorcols):
            if (menteeFields[m][i]==mentorFields[m][j] and menteeFields[m][i] !=0 and menteeFields[m][i] !='0' and mentorFields[m][j] !=0 and mentorFields[m][j] !='0'):
                col.append(1)
            else :
                col.append(0)
        arr.append(col)
    MatchFields.append(arr)
    print("\n",arr)
print("\n******************\n",MatchFields)
# rows=no of fields
#columns=No of mentees
# columns in the sub-array =no of mentors

#creating a 2D array
'''Menteerows, Mentorcols = (len(menteeFields[9]),len(mentorFields[9]))
arr=[]
for i in range(Menteerows):
    col = []
    for j in range(Mentorcols):
        if (menteeFields[9][i]==mentorFields[9][j] and menteeFields[9][i] !='0' and mentorFields[9][j] !='0'):
            col.append(1)
        else :
            col.append(0)
    arr.append(col)
print("\n",arr)'''
# rows=no of mentees
#columns=No of mentors

                   


 [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

 [[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0

'Menteerows, Mentorcols = (len(menteeFields[9]),len(mentorFields[9]))\narr=[]\nfor i in range(Menteerows):\n    col = []\n    for j in range(Mentorcols):\n        if (menteeFields[9][i]==mentorFields[9][j] and menteeFields[9][i] !=\'0\' and mentorFields[9][j] !=\'0\'):\n            col.append(1)\n        else :\n            col.append(0)\n    arr.append(col)\nprint("\n",arr)'

In [5]:
# importing library
arr = np.array(MatchFields)
column_sums = arr.sum(axis=0)
#column_sums


In [6]:
timezone= [
['GMT',0],
['UTC',0],
['ECT',1],
['EET',2],
['ART',2],
['EAT',3],
['MET',3.5],
['NET',4],
['PLT',5],
['IST',5.5],
['BST',6],
['VST',7],
['CTT',8],
['JST',9],
['ACT',9.5],
['AET',10],
['SST',11],
['NST',12],
['MIT',-11],
['HST',-10],
['AST',-9],
['PST',-8],
['PNT',-7],
['MST',-7],
['CST',-6],
['EST',-5],
['IET',-5],
['PRT',-4],
['CNT',-3.5],
['AGT',-3],
['BET',-3],
['CAT',-1]]

mentorTimezone=list(mentor['dropdownMenuButton'])
menteeTimezone=list(mentee['dropdownMenuButton2'])
print(mentorTimezone)
menteeTimezone


aTime=[]
bTime=[]
for i in range(len(mentorTimezone)):
    for t in range(len(timezone)):
        if (timezone[t][0]==mentorTimezone[i]):
            aTime.append(timezone[t][1])

for i in range(len(menteeTimezone)):
    for t in range(len(timezone)):
        if (timezone[t][0]==menteeTimezone[i]):
            bTime.append(timezone[t][1])

#print('aTime',aTime)
#print('bTime',bTime)

#creating a 2D array
rows, cols = (len(bTime), len(aTime))
arr=[]
for i in range(rows):
    col = []
    for j in range(cols):
        col.append(abs(aTime[j]-bTime[i]))
    arr.append(col)
#print("\n",arr)
# Ranking of array in reverse order
timeRank=[]
from scipy.stats import rankdata
for i in range (len(arr)) :
    timeRank.append(rankdata(arr[i], method='dense'))
#print(timeRank) #Ranked 2D array'''

timeRank2=[]
for i in range (len(timeRank)) :
    timeRank2.append(max(timeRank[i]) - rankdata(arr[i], method='dense')+1)
timeRank2=np.array(timeRank2)
print(timeRank2) #Reveresed 2D Ranked array'''



['EST', 'IST', 'IST', 'EET', 'PRT', 'IST', 'PRT', 'MST', 'IST', 'IST', 'IST']
[[4 1 1 2 5 1 5 3 1 1 1]
 [4 1 1 2 5 1 5 3 1 1 1]
 [5 1 1 2 4 1 4 3 1 1 1]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [4 1 1 2 3 1 3 5 1 1 1]
 [4 1 1 2 3 1 3 5 1 1 1]
 [5 1 1 2 4 1 4 3 1 1 1]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [2 5 5 4 3 5 3 1 5 5 5]
 [4 1 1 2 3 1 3 5 1 1 1]]


In [7]:
mentorHour=mentor['Availability']
menteeHour=mentee['Availability2']
print(mentorHour)
#creating a 2D array
rows, cols = (len(menteeHour), len(mentorHour))
arr=[]
for i in range(rows):
    col = []
    for j in range(cols):
        col.append(abs(mentorHour[j]-menteeHour[i]))
    arr.append(col)
#print("\n",arr)
# Ranking of array in reverse order
hourRank=[]
from scipy.stats import rankdata
for i in range (len(arr)) :
    hourRank.append(rankdata(arr[i], method='dense'))
#print(hourRank) #Ranked 2D array'''
hourRank2=[]
for i in range (len(hourRank)) :
    hourRank2.append(max(hourRank[i]) - rankdata(arr[i], method='dense')+1)
hourRank2=np.array(hourRank2)
print(hourRank2) #Reveresed 2D Ranked array'''



0      2
1      5
2      4
3      4
4      5
5      7
6      2
7      1
8      3
9      6
10    10
Name: Availability, dtype: int64
[[7 4 5 5 4 2 7 6 6 3 1]
 [7 4 5 5 4 2 7 6 6 3 1]
 [7 4 5 5 4 2 7 6 6 3 1]
 [2 5 4 4 5 7 2 1 3 6 8]
 [2 5 4 4 5 7 2 1 3 6 4]
 [2 5 4 4 5 7 2 1 3 6 8]
 [2 5 4 4 5 7 2 1 3 6 8]
 [2 5 4 4 5 7 2 1 3 6 4]
 [2 5 4 4 5 7 2 1 3 6 4]
 [2 5 4 4 5 7 2 1 3 6 4]
 [3 6 5 5 6 4 3 2 4 5 1]
 [3 6 5 5 6 4 3 2 4 5 1]
 [2 5 4 4 5 7 2 1 3 6 8]
 [7 4 5 5 4 2 7 6 6 3 1]
 [5 4 5 5 4 2 5 4 6 3 1]
 [5 4 5 5 4 2 5 4 6 3 1]
 [7 4 5 5 4 2 7 8 6 3 1]
 [2 5 4 4 5 7 2 1 3 6 8]
 [2 5 4 4 5 7 2 1 3 6 8]
 [2 5 4 4 5 7 2 1 3 6 8]
 [7 4 5 5 4 2 7 8 6 3 1]]


In [8]:
finalRankedArray=[]
finalRankedArray.append(column_sums)
finalRankedArray.append(timeRank2)
finalRankedArray.append(hourRank2)
finalRankedArray=np.array(finalRankedArray)
print(finalRankedArray)

[[[1 0 0 0 0 1 0 0 0 0 2]
  [0 1 1 1 0 0 0 0 1 3 3]
  [1 1 1 1 1 1 0 1 1 4 8]
  [0 0 0 0 0 0 0 0 0 1 1]
  [0 0 1 1 1 1 0 0 0 3 5]
  [0 1 0 0 1 0 0 0 1 3 5]
  [0 1 1 1 1 0 0 0 1 4 5]
  [0 0 1 1 1 0 0 0 0 3 4]
  [0 0 1 1 1 0 1 1 0 3 5]
  [1 1 1 1 1 1 1 1 1 4 8]
  [0 1 1 1 1 0 0 0 1 3 5]
  [0 1 0 0 1 0 0 0 1 2 4]
  [1 1 0 0 0 1 0 0 1 2 4]
  [1 1 0 0 0 0 0 0 1 1 2]
  [1 0 0 0 0 0 0 1 0 1 2]
  [1 1 1 1 1 1 1 1 1 4 8]
  [1 1 0 0 0 1 0 0 1 1 3]
  [0 1 0 0 1 0 0 0 1 3 5]
  [0 1 1 1 1 1 0 0 1 4 6]
  [0 1 0 0 1 0 0 0 1 2 3]
  [1 1 1 1 0 1 0 0 1 3 6]]

 [[4 1 1 2 5 1 5 3 1 1 1]
  [4 1 1 2 5 1 5 3 1 1 1]
  [5 1 1 2 4 1 4 3 1 1 1]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [2 5 5 4 3 5 3 1 5 5 5]
  [4 1 1 2 3 1 3 5 1 1 1]
  [4 1 1 2 3 1 3 5 1 1 1]
  [5 1 1 2 4 1 4 3 1 1 1]
  [2 5 5 4

In [9]:
finalRankedArray=finalRankedArray.sum(axis=0)
print(finalRankedArray)

[[12  5  6  7  9  4 12  9  7  4  4]
 [11  6  7  8  9  3 12  9  8  7  5]
 [13  6  7  8  9  4 11 10  8  8 10]
 [ 4 10  9  8  8 12  5  2  8 12 14]
 [ 4 10 10  9  9 13  5  2  8 14 14]
 [ 4 11  9  8  9 12  5  2  9 14 18]
 [ 4 11 10  9  9 12  5  2  9 15 18]
 [ 4 10 10  9  9 12  5  2  8 14 13]
 [ 4 10 10  9  9 12  6  3  8 14 14]
 [ 5 11 10  9  9 13  6  3  9 15 17]
 [ 5 12 11 10 10  9  6  3 10 13 11]
 [ 5 12 10  9 10  9  6  3 10 12 10]
 [ 5 11  9  8  8 13  5  2  9 13 17]
 [10 10 10  9  7  7 10  7 12  9  8]
 [10  5  6  7  7  3  8 10  7  5  4]
 [10  6  7  8  8  4  9 10  8  8 10]
 [13  6  6  7  8  4 11 11  8  5  5]
 [ 4 11  9  8  9 12  5  2  9 14 18]
 [ 4 11 10  9  9 13  5  2  9 15 19]
 [ 4 11  9  8  9 12  5  2  9 13 16]
 [12  6  7  8  7  4 10 13  8  7  8]]


In [10]:
#The Pairing Algo :
from pulp import *
prob = LpProblem("Matching Employees", LpMaximize)

c = finalRankedArray
MenteeNames =mentee['email2']
MentorNames =mentor['email']

match_info = pd.DataFrame(c, index=MenteeNames, columns=MentorNames)

print(match_info)


email                         durginv@gmail.com  \
email2                                            
ananya.gollakota@gmail.com                   12   
arianneghislaine@gmail.com                   11   
jding713@gmail.com                           13   
bvanshika264@gmail.com                        4   
gayatrivb26@gmail.com                         4   
vnikhita28@gmail.com                          4   
harisapnanair@yahoo.in                        4   
durwapatil30@gmail.com                        4   
priyankawakalkar07@gmail.com                  4   
jkavita8935@gmail.com                         5   
bhambrilavisha@gmail.com                      5   
khushigarg94@gmail.com                        5   
simararora947@gmail.com                       5   
gpurohit74@gmail.com                         10   
matilyn@gmail.com                            10   
revaga901@gmail.com                          10   
morisgruslova@yahoo.com                      13   
likamona16@gmail.com           

C:\ProgramData\Anaconda3\lib\site-packages\pulp\pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


In [13]:

MenteeNames =mentee['name2']
MentorNames =mentor['name']
MentorIndex=[]
for i in range (len(finalRankedArray)):
    maximum=max(finalRankedArray[i])
    for j in range (len(finalRankedArray[0])):
        if maximum==finalRankedArray[i][j]:
            MentorIndex.append(j)

print(MentorIndex)
print(MenteeNames)

[0, 6, 6, 0, 10, 9, 10, 10, 10, 9, 9, 10, 10, 9, 1, 9, 10, 8, 0, 7, 0, 7, 10, 0, 10, 10, 10, 7]
0           Ananya Gollakota
1     Arianne Ghislaine Rull
2                 Julia Ding
3            Vanshika Bansal
4            Gayatri Bhosale
5                  V Nikhita
6            Hari Sapna Nair
7                Durwa Patil
8          Priyanka Wakalkar
9              Kavita Jagtap
10           Lavisha Bhambri
11               Khushi Garg
12           Simarpreet Kaur
13        Geetanjali Purohit
14              Matilyn Wang
15              Reva Agarwal
16           Tamara Gruslova
17           Monalika Kapoor
18       Vedurumudi Priyanka
19               Nisha Yadav
20              Zeynep Yakay
Name: name2, dtype: object


In [14]:
for i in range (len(finalRankedArray)):
    maximum=max(finalRankedArray[i])
    for j in range (len(finalRankedArray[0])):
        if j==MentorIndex[i]:
            print('{} and {} with Total score: {}'.format(MenteeNames[i],MentorNames[j],finalRankedArray[i][j]))



Ananya Gollakota and Veronika Durgin with Total score: 12
Arianne Ghislaine Rull and Mariah Villalon with Total score: 12
Julia Ding and Mariah Villalon with Total score: 11
Vanshika Bansal and Veronika Durgin with Total score: 4
Gayatri Bhosale and Yash Patel with Total score: 14
V Nikhita and Ankit Kumar with Total score: 14
Hari Sapna Nair and Yash Patel with Total score: 18
Durwa Patil and Yash Patel with Total score: 13
Priyanka Wakalkar and Yash Patel with Total score: 14
Kavita Jagtap and Ankit Kumar with Total score: 15
Lavisha Bhambri and Ankit Kumar with Total score: 13
Khushi Garg and Yash Patel with Total score: 10
Simarpreet Kaur and Yash Patel with Total score: 17
Geetanjali Purohit and Ankit Kumar with Total score: 9
Matilyn Wang and Spriha Ghosh with Total score: 5
Reva Agarwal and Ankit Kumar with Total score: 8
Tamara Gruslova and Yash Patel with Total score: 5
Monalika Kapoor and Prahitha Movva with Total score: 9
Vedurumudi Priyanka and Veronika Durgin with Total sc